export  default  class CommonConstants{
  /**
   * Full width or height.
   */
  static readonly FULL_LENGTH: string = '100%';

  /**
   * Title height.
   */
  static readonly TITLE_WIDTH: string = '80%';

  /**
   * List default width.
   */
  static readonly LIST_DEFAULT_WIDTH: string = '93.3%';

  /**
   * Opacity of default.
   */
  static readonly OPACITY_DEFAULT: number = 1;

  /**
   * Opacity of default.
   */
  static readonly OPACITY_COMPLETED: number = 0.4;

  /**
   * BorderRadius of list item.
   */
  static readonly BORDER_RADIUS: number = 24;

  /**
   * BorderRadius of list item.
   */
  static readonly FONT_WEIGHT: number = 500;

  /**
   * Space of column.
   */
  static readonly COLUMN_SPACE: number = 16;

  /**
   * agents data.
   */
  static readonly TODO_DATA: Array<string> = [
    "三国演义",
    "红楼梦",
    "水浒传",
    "西游记",
    "儒林外史"
  ];

  static readonly WEB_ALERT_DIALOG_TEXT_VALUE: ResourceStr = $r('app.string.congratulate');


  static readonly WEB_CONSTANT_FULL_WIDTH: string = '100%';
  static readonly WEB_CONSTANT_FULL_HEIGHT: string = '100%';
  static readonly WEB_CONSTANT_WIDTH: string = '93.3%';
  static readonly WEB_CONSTANT_HEIGHT: string = '55.9%';
  static readonly WEB_CONSTANT_MARGIN_TOP: string = '7.1%';
  static readonly WEB_CONSTANT_MARGIN_LEFT: string = '3.3%';
  static readonly WEB_CONSTANT_MARGIN_RIGHT: string = '3.3%';
  static readonly WEB_CONSTANT_TOP_ROW_HEIGHT: string = '7.2%';
  static readonly WEB_CONSTANT_IMAGE_WIDTH: string = '5.6%';
  static readonly WEB_CONSTANT_IMAGE_HEIGHT: string = '32%';
  static readonly WEB_CONSTANT_IMAGE_MARGIN_LEFT: string = '7.2%';
  static readonly WEB_CONSTANT_TEXT_VALUE_WIDTH: string = '35.6%';
  static readonly WEB_CONSTANT_TEXT_VALUE_HEIGHT: string = '3.1%';
  static readonly WEB_CONSTANT_TEXT_VALUE_MARGIN_TOP: string = '3.1%';
  static readonly WEB_CONSTANT_TEXT_VALUE_FONT_SIZE: number = 18;
  static readonly WEB_CONSTANT_TEXT_VALUE_FONT_WEIGHT: number = 500;
  static readonly WEB_CONSTANT_TIP_TEXT_VALUE_WIDTH: string = '15.6%';
  static readonly WEB_CONSTANT_TIP_TEXT_VALUE_HEIGHT: string = '2.4%';
  static readonly WEB_CONSTANT_TIP_TEXT_VALUE_FONT_SIZE: number = 14;
  static readonly WEB_CONSTANT_TIP_TEXT_VALUE_MARGIN_TOP: string = '0.9%';
  static readonly WEB_CONSTANT_TIP_TEXT_VALUE_OPACITY: number = 0.6;
  static readonly WEB_CONSTANT_TOP_TEXT_WIDTH: string = '82.2%';
  static readonly WEB_CONSTANT_TOP_TEXT_HEIGHT: string = '50%';
  static readonly WEB_CONSTANT_TOP_TEXT_MARGIN_LEFT: string = '5%';
  static readonly WEB_CONSTANT_TOP_TEXT_FONT_SIZE: number = 20;
  static readonly WEB_CONSTANT_BUTTON_WIDTH: string = '86.7%';
  static readonly WEB_CONSTANT_BUTTON_HEIGHT: string = '5.1%';
  static readonly WEB_CONSTANT_BUTTON_MARGIN_TOP: string = '10%';
  static readonly WEB_CONSTANT_BUTTON_BORDER_RADIUS: string = '20';
  static readonly WEB_CONSTANT_BUTTON_FONT_SIZE: number = 16;
  static readonly WEB_CONSTANT_DURATION: number = 3000;
  static readonly WEB_CONSTANT_PROGRESS_MIN: number = 0;
  static readonly WEB_CONSTANT_PROGRESS_MAX: number = 100;
  static readonly WEB_CONSTANT_PROGRESS_STEP: number = 10;
  static readonly WEB_CONSTANT_MILLI_SECONDS: number = 100;
  static readonly WEB_CONSTANT_PROGRESS_STROKE_WIDTH: number = 15;
  static readonly WEB_CONSTANT_PROGRESS_SCALE_COUNT: number = 15;
  static readonly WEB_CONSTANT_PROGRESS_SCALE_WIDTH: number = 5;
  static readonly WEB_CONSTANT_PROGRESS_WIDTH: number = 80;
  static readonly WEB_CONSTANT_PROGRESS_POSITION_X: string = '40%';
  static readonly WEB_CONSTANT_PROGRESS_POSITION_Y: string = '30%';
  static readonly MAIN_CONSTANT_FULL_HEIGHT: string = '100%';
  static readonly MAIN_CONSTANT_IMAGE_HEIGHT: string = '38.7%';
  static readonly MAIN_CONSTANT_BUTTON_MARGIN_TOP_BUTTON: string = '3.1%';
  static readonly MAIN_CONSTANT_BUTTON_HEIGHT: string = '5.1%';
  static readonly MAIN_CONSTANT_BUTTON_MARGIN_TOP: string = '4.6%';
  static readonly MAIN_CONSTANT_BUTTON_WIDTH: string = '86.7%';
  static readonly MAIN_CONSTANT_BUTTON_BORDER_RADIUS: number = 20;
  static readonly MAIN_CONSTANT_BUTTON_FONT_SIZE: number = 16;

}